// Code generated by oasmith. DO NOT EDIT.
#![allow(dead_code, clippy::large_enum_variant, clippy::enum_variant_names)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientConfig {
    #[serde(rename = "api_origin")]
    pub api_origin: std::string::String,
    #[serde(rename = "dashboard_origin")]
    pub dashboard_origin: std::string::String,
}

