defaultProject: client
projects:
  youtubejs: vendor
  client: .
  cli: crates/cli
  client-engine: crates/sync-engine
  client-youtubei: crates/youtubei
  desktop: crates/desktop
versionConstraint: ">=2.5.4 <3.0.0"
vcs:
  client: git
  defaultBranch: master
pipeline:
  installDependencies: false
  syncProjects: false
  syncWorkspace: false
hasher:
  walkStrategy: glob
